name: 🚀 CI/CD - Python Guestbook

# Eventos que disparan el pipeline
on:
  push:
    branches:
      - main     # Despliegue de Producción (CD)
      - develop  # Integración Continua (CI)
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch: # Permite ejecutar el pipeline manualmente

env:
  DOCKER_IMAGE_NAME: guestbook-frontend

jobs:
  # -------------------------------------------------------------------------
  # JOB 1: INTEGRACIÓN CONTINUA (CI) - Se ejecuta en main, develop y Pull Requests
  # -------------------------------------------------------------------------
  ci:
    name: 🧪 Continuous Integration Checks
    runs-on: ubuntu-latest

    services:
      # Configura un servicio Redis temporal para las pruebas de CI
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: --health-cmd "redis-cli ping" --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: ⬇️ Checkout Code (Full History)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Necesario para SonarCloud SCM y Git info

      - name: 🐍 Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: 📦 Install dependencies
        run: pip install -r requirements.txt
        
      - name: 🔎 Run Linting (Flake8)
        run: |
          pip install flake8
          flake8 app tests

      # 🧪 1. Ejecutar Tests y generar el informe de cobertura
      - name: 🧪 Run Tests with Coverage
        # Usa el nombre del servicio Redis configurado arriba
        env:
          REDIS_HOST: localhost 
        run: |
          pip install pytest coverage
          # Usa el puerto mapeado (6379)
          coverage run --source=app -m pytest tests/
          coverage xml -o coverage-report.xml

      # 🛡️ 2. Análisis de Vulnerabilidades (Snyk)
      - name: 🛡️ Run Snyk Security Scan
        uses: snyk/actions/python-3.11@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          args: --file=requirements.txt

      # 📊 3. Análisis Estático de Código (SonarCloud)
      - name: 📊 SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=naesman1
            -Dsonar.projectKey=naesman1_guestbook-cicd
            -Dsonar.sources=app/
            -Dsonar.tests=tests/
            -Dsonar.python.coverage.reportPaths=coverage-report.xml
            -Dsonar.scm.disabled=true # Soluciona el error de rama en el scanner

  # -------------------------------------------------------------------------
  # JOB 2: DESPLIEGUE CONTINUO (CD) - SOLO se ejecuta si la rama es MAIN
  # -------------------------------------------------------------------------
  deploy:
    name: 🚀 Continuous Deployment (MAIN Branch Only)
    needs: ci
    if: success() && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout Application Code
        uses: actions/checkout@v4
        
      - name: ⚙️ Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: 🔐 Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 🏗️ Build y Push con doble tag: SHA + latest
      - name: 🏗️ Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }}
            ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:latest

      # ⚙️ GitOps: Actualiza el Repositorio de Configuración
      - name: ⬇️ Checkout Kubernetes Config Repo
        uses: actions/checkout@v4
        with:
          repository: naesman1/guestbook-k8s-config
          token: ${{ secrets.GH_TOKEN }} 
          path: config-repo

      # 🏷️ Actualiza el tag de imagen en el manifiesto automáticamente
      - name: 🏷️ Update Kubernetes Manifest Tag (Auto SED)
        run: |
          cd config-repo
          FILE="k8s/frontend-deployment.yaml"
          IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}"
          NEW_TAG="${{ github.sha }}"

          # Reemplaza cualquier tag existente en la línea de la imagen
          sed -i -E "s|(${IMAGE_NAME}):[a-zA-Z0-9._-]+|\1:${NEW_TAG}|g" $FILE

      # ⬆️ Commit y push al repo de configuración (dispara ArgoCD)
      - name: ⬆️ Commit and Push to GitOps Repo (Trigger ArgoCD)
        run: |
          cd config-repo
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add k8s/frontend-deployment.yaml
          git commit --allow-empty -m "chore(cd): update image tag to ${{ github.sha }}"
          git push
